# Generated by Django 3.2.3 on 2021-07-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Ingrese rut sin guion')),
                ('correo', models.CharField(max_length=50, verbose_name='Ingrese correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Ingrese nombre completo')),
                ('contraseña', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Ingrese rut sin guion')),
                ('correo', models.CharField(max_length=50, verbose_name='Ingrese correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Ingrese nombre completo')),
                ('contraseña', models.CharField(max_length=50)),
                ('asistencia', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreAsignatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Ingrese rut sin guion')),
                ('correo', models.CharField(max_length=50, verbose_name='Ingrese correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Ingrese nombre completo')),
                ('contraseña', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaAlumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.alumno')),
                ('notaAsignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombreCurso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alumnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.profesor'),
        ),
    ]
