# Generated by Django 3.2.3 on 2021-06-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('notas', models.CharField(max_length=50)),
                ('asistencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ingrese correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Ingrese nombre completo')),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('correo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombrecurso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alumnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usuario')),
            ],
        ),
    ]
