# Generated by Django 3.2.3 on 2021-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='nombre',
            new_name='nombreAsignatura',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombrecurso',
            new_name='nombreCurso',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='asistencia',
            field=models.FloatField(max_length=50),
        ),
    ]
