# Generated by Django 3.2.3 on 2021-07-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210705_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='notaAlumno',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='notaAsignatura',
        ),
        migrations.AddField(
            model_name='notas',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='notas',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='notas',
            name='evaluacion',
            field=models.CharField(blank=True, choices=[('01', 'Prueba'), ('02', 'Control'), ('03', 'Taller'), ('04', 'Diagnostico')], default=None, max_length=15, null=True, verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 2'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 3'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 4'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 5'),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota_6',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota 6'),
        ),
        migrations.AddField(
            model_name='notas',
            name='promedio',
            field=models.FloatField(blank=True, null=True, verbose_name='Promedio'),
        ),
    ]
